services:
  ca-tls:
    container_name: ca-tls
    image: hyperledger/fabric-ca
    command: sh -c 'fabric-ca-server start -b tlsadmin:tlsadminpw --port 7052'
    environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=ca-tls
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
    volumes:
      - /tmp/hyperledger/ca-tls:/tmp/hyperledger/fabric-ca/crypto
    networks:
      - fabric-ca
    ports:
      - 7052:7052

  ca-org0:
    container_name: ca-org0
    image: hyperledger/fabric-ca
    command: sh -c 'fabric-ca-server start -b org0admin:org0adminpw --port 7053'
    environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=ca-org0
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
    volumes:
      - /tmp/hyperledger/ca-org0:/tmp/hyperledger/fabric-ca/crypto
    networks:
      - fabric-ca
    ports:
      - 7053:7053

  ca-org1:
    container_name: ca-org1
    image: hyperledger/fabric-ca
    command: sh -c 'fabric-ca-server start -b org1admin:org1adminpw --port 7054'
    environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=ca-org1
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
    volumes:
      - /tmp/hyperledger/ca-org1:/tmp/hyperledger/fabric-ca/crypto
    networks:
      - fabric-ca
    ports:
      - 7054:7054

  ca-org2:
    container_name: ca-org2
    image: hyperledger/fabric-ca
    command: sh -c 'fabric-ca-server start -b org2admin:org2adminpw --port 7055'
    environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=ca-org2
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
    volumes:
      - /tmp/hyperledger/ca-org2:/tmp/hyperledger/fabric-ca/crypto
    networks:
      - fabric-ca
    ports:
      - 7055:7055

networks:
  fabric-ca: