Organizations:
  - &org0
    Name: org0
    ID: org0MSP
    MSPDir: ./data/org0/msp

  - &org1
    Name: org1
    ID: org1MSP
    MSPDir: ./data/org1/msp
    AnchorPeers:
      - Host: peer1-org1
        Port: 7051

  - &org2
    Name: org2
    ID: org2MSP
    MSPDir: ./data/org2/msp
    AnchorPeers:
      - Host: peer1-org2
        Port: 7051

  - &org2
    Name: org3
    ID: org3MSP
    MSPDir: ./data/org3/msp
    AnchorPeers:
      - Host: peer1-org3
        Port: 7051

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true

  Orderer: &OrdererCapabilities
    V2_0: true

  Application: &ApplicationCapabilities
    V2_0: true
