services:
  ca-org0:
    container_name: ca-org0
    command: /bin/bash -c 'fabric-ca-server start -b admin:adminpw --port 7052'
    environment:
      - FABRIC_CA_SERVER_HOME=/hyperledger/crypto
      - FABRIC_CA_SERVER_CSR_CN=ca-org0
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
    image: hyperledger/fabric-ca:latest
    ports:
      - 7052:7052
    networks:
      - fabric
    volumes:
      - ./data/ca-org0:/hyperledger/
    
  ca-org1:
    container_name: ca-org1
    command: /bin/bash -c 'fabric-ca-server start -b admin:adminpw --port 7053'
    environment:
      - FABRIC_CA_SERVER_HOME=/hyperledger/crypto
      - FABRIC_CA_SERVER_CSR_CN=ca-org1
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
    image: hyperledger/fabric-ca:latest
    ports:
      - 7053:7053
    networks:
      - fabric
    volumes:
      - ./data/ca-org1:/hyperledger/

  ca-org2:
    container_name: ca-org2
    command: /bin/bash -c 'fabric-ca-server start -b admin:adminpw --port 7054'
    environment:
      - FABRIC_CA_SERVER_HOME=/hyperledger/crypto
      - FABRIC_CA_SERVER_CSR_CN=ca-org2
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
    image: hyperledger/fabric-ca:latest
    ports:
      - 7054:7054
    networks:
      - fabric
    volumes:
      - ./data/ca-org2:/hyperledger/

  ca-org3:
    container_name: ca-org3
    command: /bin/bash -c 'fabric-ca-server start -b admin:adminpw --port 7055'
    environment:
      - FABRIC_CA_SERVER_HOME=/hyperledger/crypto
      - FABRIC_CA_SERVER_CSR_CN=ca-org3
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
    image: hyperledger/fabric-ca:latest
    ports:
      - 7055:7055
    networks:
      - fabric
    volumes:
      - ./data/ca-org3:/hyperledger/

  orderer1-org0:
    container_name: orderer1-org0
    image: hyperledger/fabric-orderer:2.4
    environment:
      - FABRIC_CFG_PATH=/hyperledger/org0/orderer
    volumes:
      - ./data/org0/orderer:/hyperledger/org0/orderer
    networks:
      - fabric

  peer1-org1:
    container_name: peer1-org1
    image: hyperledger/fabric-peer:2.4
    environment:
      - CORE_PEER_ID=peer1-org1
      - CORE_PEER_ADDRESS=peer1-org1:7051
      - CORE_PEER_LOCALMSPID=UsersMSP
      - CORE_PEER_MSPCONFIGPATH=/hyperledger/org1/peer1/msp
    volumes:
      - ./data/org1/peer1:/hyperledger/org1/peer1
    links:
      - orderer1-org0
    networks:
    - fabric

networks:
  fabric: